version: '3'

services:
  web:
    build: .
    image: openclass:0.3
    volumes:
      - ./OpenClass:/opt/OpenClass
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=openclass
      - POSTGRES_USER=openclass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
