version: '3'

services:
  web:
    build: .
    image: openclass:0.1
    volumes:
      - ./OpenClass:/opt/OpenClass
    ports:
      - "8000:8000"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=openclass
      - POSTGRES_USER=openclass
