version: '2'

services:
  web:
    build: .
    image: openclass:0.3
    volumes:
      - ./OpenClass:/opt/OpenClass
    ports:
      - "80:8000"
    depends_on:
      - "db"
      - "db_redis"
    restart: on-failure
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=openclass
      - POSTGRES_USER=openclass
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_redis:
    image: redis:alpine
    volumes:
      - redis_data:/data


volumes:
  pgdata:
  redis_data:
